"""Pydantic models forming the public core contract."""

from .advice import Advice, GlobalRepairSession, RepairDecision
from .common import (
    ArtifactRef,
    CodeAnchor,
    CoverageSelfReport,
    DossierEntry,
    DossierEntryKind,
    MigrationRulebook,
    RulebookEntry,
    RulebookEntryKind,
    RuleEntrySource,
    TargetProjectBlueprint,
    UnderstandingDossier,
)
from .context import ContextPack, ContextPackIdentity, SessionBudgetProfile, SliceGenerationRef
from .descriptor import (
    CheckCommandTemplate,
    ContractArtifact,
    ManifestParserRef,
    RequiredCheck,
    SourceToolchain,
    TargetToolchain,
    ToolchainDescriptor,
    TreeSitterGrammarRef,
)
from .plan import PlanEdge, PlanProposal, PlanValidation
from .run import (
    CreateRun,
    CreateRunSource,
    FrozenArtifactBundle,
    GitRunRefs,
    RegisteredProject,
    RemoteRepository,
)
from .slice import ActiveDispatch, MigrationSlice, SliceCandidate, WriteScope, WriteScopeOut
from .verification import (
    CheckResult,
    DiagnosticMapping,
    DiagnosticTarget,
    ExecutionSubject,
    FileLine,
    FinalVerified,
    LocalCandidate,
    ProspectiveIntegration,
    RepairEvidence,
    TestIdentity,
    Unknown,
    VerificationOutcome,
    VerificationSubject,
)

__all__ = [
    "ActiveDispatch",
    "Advice",
    "ArtifactRef",
    "CheckCommandTemplate",
    "CheckResult",
    "CodeAnchor",
    "ContextPack",
    "ContextPackIdentity",
    "ContractArtifact",
    "CreateRun",
    "CreateRunSource",
    "CoverageSelfReport",
    "DiagnosticMapping",
    "DiagnosticTarget",
    "DossierEntry",
    "DossierEntryKind",
    "ExecutionSubject",
    "FileLine",
    "FinalVerified",
    "FrozenArtifactBundle",
    "GitRunRefs",
    "GlobalRepairSession",
    "LocalCandidate",
    "ManifestParserRef",
    "MigrationRulebook",
    "MigrationSlice",
    "PlanEdge",
    "PlanProposal",
    "PlanValidation",
    "ProspectiveIntegration",
    "RegisteredProject",
    "RepairDecision",
    "RepairEvidence",
    "RemoteRepository",
    "RequiredCheck",
    "RulebookEntry",
    "RulebookEntryKind",
    "RuleEntrySource",
    "SessionBudgetProfile",
    "SliceCandidate",
    "SliceGenerationRef",
    "SourceToolchain",
    "TargetProjectBlueprint",
    "TargetToolchain",
    "TestIdentity",
    "ToolchainDescriptor",
    "TreeSitterGrammarRef",
    "Unknown",
    "UnderstandingDossier",
    "VerificationOutcome",
    "VerificationSubject",
    "WriteScope",
    "WriteScopeOut",
]
