from codemigrator.core.enums import (
    AdviceKind,
    ArtifactKind,
    CheckAction,
    CheckStatus,
    CorrectionIntentStatus,
    DeliveryChannelStatus,
    DiagnosticSeverity,
    DossierBudgetTier,
    FailureReason,
    InteractionStatus,
    MigrationSessionStatus,
    ModelProfile,
    ModuleBoundaryStrategy,
    Phase,
    PlanEdgeKind,
    ResidentRole,
    RunStatus,
    SessionKind,
    SliceAttemptStatus,
    SliceKind,
)


def enum_values(enum_type: type) -> list[str]:
    return [member.value for member in enum_type]


def test_m00_enum_values_are_exact() -> None:
    expected = {
        MigrationSessionStatus: ["Drafting", "ReadyToConfirm", "AttachedToRun", "Closed"],
        InteractionStatus: ["Ready", "PausingForInput", "WaitingForUser", "ApplyingCorrection"],
        CorrectionIntentStatus: [
            "Received",
            "NeedsClarification",
            "NeedsConfirmation",
            "Accepted",
            "Applied",
            "DeferredToFollowUp",
            "Rejected",
        ],
        SliceKind: ["CONTRACT", "IMPLEMENTATION", "TEST_TRANSLATION", "TEST_GENERATION"],
        ArtifactKind: ["GENERATED_CODE", "DECLARATIVE_CONFIG", "RESOURCE_FILE"],
        DossierBudgetTier: ["Shallow", "Deep"],
        SliceAttemptStatus: [
            "READY",
            "RUNNING",
            "LOCAL_VERIFYING",
            "LOCALLY_VERIFIED",
            "INTEGRATION_QUEUED",
            "INTEGRATING",
            "REGENERATING",
            "INTEGRATED",
            "TERMINAL_FAILED",
            "CANCELLED",
        ],
        PlanEdgeKind: ["REQUIRES", "ORDERED_BEFORE"],
        RunStatus: [
            "CREATED",
            "PLANNING",
            "EXECUTING",
            "VERIFYING",
            "REPORTING",
            "COMPLETED",
            "PARTIALLY_COMPLETED",
            "FAILED",
            "CANCELLED",
        ],
        FailureReason: [
            "ANALYSIS_FAILED",
            "DOSSIER_INCONSISTENT",
            "PLAN_FAILED",
            "EXECUTION_FAILED",
            "VERIFICATION_TERMINAL",
            "REPORT_GENERATION_FAILED",
            "BUDGET_EXHAUSTED",
            "RESOURCE_EXHAUSTED",
            "OUTPUT_LIMIT_EXCEEDED",
            "SLICE_REGENERATION_EXHAUSTED",
            "NONDETERMINISTIC_VERIFICATION",
        ],
        DeliveryChannelStatus: ["PENDING", "GENERATING", "READY", "DELIVERY_FAILED"],
        ModelProfile: ["REASONING", "CODE"],
        Phase: ["PLAN", "EXECUTE", "VERIFY", "REPORT"],
        ResidentRole: ["EXPLORE_COORDINATOR", "EXECUTE_SUPERVISOR"],
        AdviceKind: [
            "EXPLORE_REASSIGNMENT",
            "REPAIR_DECISION",
            "ROUTE_SUGGESTION",
            "PLAN_REVISION",
            "ASK_USER",
        ],
        ModuleBoundaryStrategy: [
            "MANIFEST_PER_MODULE",
            "SINGLE_MANIFEST_DIRECTORY_CONVENTION",
            "DIRECTORY_CONVENTION",
        ],
        CheckAction: ["SCAFFOLD", "COMPILE", "TEST", "LINT", "TYPE_CHECK"],
        DiagnosticSeverity: ["Error", "Warning"],
        CheckStatus: ["PASSED", "FAILED", "TIMED_OUT", "OUTPUT_LIMIT_EXCEEDED", "INFRASTRUCTURE_ERROR"],
        SessionKind: [
            "ANALYZE_AUXILIARY",
            "PLAN_AUXILIARY",
            "CONTRACT",
            "IMPLEMENTATION",
            "TEST_TRANSLATION",
            "TEST_GENERATION",
            "EXPLORE_COORDINATOR",
            "EXECUTE_SUPERVISOR",
            "REPAIR_SESSION",
        ],
    }
    for enum_type, values in expected.items():
        assert enum_values(enum_type) == values
        assert all(isinstance(member, str) for member in enum_type)

