from codemigrator.core.errors import StableErrorCode


def test_stable_error_codes_are_single_string_enum() -> None:
    expected = {
        "TOOL_PHASE_DENIED",
        "TOOL_NOT_FOUND",
        "TOOL_SCHEMA_INVALID",
        "PATH_DENIED",
        "READ_OUT_OF_SCOPE",
        "WRITE_SCOPE_VIOLATION",
        "EDIT_TARGET_NOT_FOUND",
        "EDIT_AMBIGUOUS",
        "READ_LIMIT_EXCEEDED",
        "WRITE_LIMIT_EXCEEDED",
        "QUERY_TIMEOUT",
        "TRUNCATED",
        "PATH_OUTSIDE_SNAPSHOT",
        "TEXT_FALLBACK_UNSUPPORTED",
        "SHELL_TIMEOUT",
        "SHELL_LIMIT_EXCEEDED",
        "EXEC_TIMEOUT",
        "EXEC_SCRIPT_ERROR",
        "STALE_VERSION",
        "IDEMPOTENCY_CONFLICT",
        "STALE_DISPATCH_RESULT",
        "CHECKPOINT_WRITE_FAILED",
        "OUTPUT_LIMIT_EXCEEDED",
        "SOURCE_FILE_TOO_LARGE",
        "ANALYSIS_INFRA_ERROR",
        "SPEC_TOO_LARGE",
        "SPEC_JSON_INVALID",
        "SPEC_DUPLICATE_KEY",
        "SPEC_DEPTH_EXCEEDED",
        "SPEC_SCHEMA_UNSUPPORTED",
        "SPEC_SCHEMA_INVALID",
        "CHECK_ACTION_UNSUPPORTED",
        "CHECK_SET_INCOMPLETE",
        "DESCRIPTOR_NOT_FOUND",
        "DESCRIPTOR_DIGEST_MISMATCH",
        "TOOLCHAIN_IMAGE_UNAVAILABLE",
        "SPEC_IN_USE",
        "PLAN_CYCLE",
        "PLAN_SCOPE_CONFLICT",
        "PLAN_BLUEPRINT_VIOLATION",
        "PLAN_COVERAGE_INVALID",
        "PLAN_SIZE_EXCEEDED",
        "PLAN_EDGE_INVALID",
        "PLAN_RANK_INCONSISTENT",
        "PLAN_PROPOSAL_INVALID",
        "CHECK_MISSING",
        "CHECK_DUPLICATE",
        "CHECK_UNEXPECTED",
        "INVOCATION_HASH_MISMATCH",
        "CONTEXT_BUDGET_EXCEEDED",
        "CONTEXT_CAPABILITY_INVALID",
        "RECOVERY_LEDGER_INCONSISTENT",
    }
    assert {code.value for code in StableErrorCode} == expected
    assert StableErrorCode.WRITE_SCOPE_VIOLATION.value == "WRITE_SCOPE_VIOLATION"
    assert all(isinstance(code.value, str) for code in StableErrorCode)
