"""Runtime composition root and deterministic Run orchestration primitives."""

from .actor import (
    ActorRegistry,
    ArchivePort,
    CancellationPort,
    CheckpointWriter,
    ContinuationPort,
    RunActor,
)
from .advice import (
    AdviceDisposition,
    AdviceValidationContext,
    AdviceValidationResult,
    advice_proposal_hash,
    evaluate_advice,
)
from .app import (
    AdvisoryLockPort,
    AppLifecycle,
    AppState,
    AsyncAdvisoryLockPort,
    AsyncAppLifecycle,
    InMemoryAdvisoryLock,
    PostgreSQLAdvisoryLock,
    RuntimeApplication,
    run_from_environment,
)
from .binding import (
    BindingError,
    ContextOverflowError,
    LockedModelBinding,
    ensure_context_fits,
    estimate_net_input_tokens,
    validate_session_admission,
)
from .budget import BudgetEvaluation, BudgetLimits, BudgetUsage, RunWallet, evaluate_budget
from .context import ContextEnvelope, ContextSegment, PromptMessage, prompt_text, render_prompt
from .contracts import (
    AdviceMessage,
    ApiCommand,
    ApiCommandPayload,
    BudgetEventMessage,
    CancelCommand,
    CreateRunCommand,
    EventSpec,
    ExecutionReceiptMessage,
    RecoveryCommandMessage,
    RunState,
    RuntimeEvent,
    RuntimeMessage,
    RuntimeSnapshot,
    SessionInputCommand,
)
from .integration import (
    IntegrationCoordinator,
    IntegrationItem,
    IntegrationStart,
    RepairRetryBudget,
)
from .loop import (
    AgentLoop,
    BudgetGate,
    CancellationGate,
    CancellationToken,
    CheckpointDecision,
    CheckpointPort,
    SessionCancelled,
    SessionProvenance,
    SessionResult,
    ToolGatewayPort,
    ToolObservation,
    UsageSink,
)
from .loop_contracts import SessionExit, SessionIdentity, SessionSpec, SessionState
from .normalizer import ModelAction, NormalizationError, NormalizedTurn, normalize_response
from .provider import (
    DEFAULT_TOOL_DEFINITIONS,
    AnthropicProvider,
    AsyncProvider,
    OpenAICompatibleProvider,
    ProviderCallIdentity,
    ProviderError,
    ProviderRegistry,
    ProviderRequest,
    ProviderResponse,
    ProviderToolCall,
    TokenUsage,
    ToolDefinition,
    UsageReceipt,
    retry_delay_for_attempt,
)
from .recovery import (
    ActorCheckpoint,
    CheckpointPolicy,
    CheckpointRestore,
    RecoveryCoordinator,
    RecoveryPlan,
    RecoveryTrigger,
    restore_checkpoint,
)
from .report import build_report
from .scheduler import FairScheduler, ReadySlice, ResourcePool
from .store import InMemoryRuntimeStore, PostgreSQLRuntimeStore, RuntimeStore, StoreCommitError
from .supervisor import SupervisorAdviceKind, SupervisorTrigger, supervisor_triggers
from .templates import CatalogError, StaticTemplateCatalog


def main() -> None:
    """Start the application using deployment-provided configuration."""

    exit_code = run_from_environment()
    if exit_code:
        raise SystemExit(exit_code)


__all__ = [
    "AgentLoop",
    "ActorRegistry",
    "ActorCheckpoint",
    "ArchivePort",
    "AdviceMessage",
    "AdviceDisposition",
    "AdviceValidationContext",
    "AdviceValidationResult",
    "AnthropicProvider",
    "AsyncProvider",
    "AsyncAdvisoryLockPort",
    "AsyncAppLifecycle",
    "ApiCommand",
    "ApiCommandPayload",
    "AdvisoryLockPort",
    "AppLifecycle",
    "AppState",
    "BindingError",
    "BudgetEvaluation",
    "BudgetGate",
    "BudgetEventMessage",
    "BudgetLimits",
    "BudgetUsage",
    "RunWallet",
    "CancelCommand",
    "CheckpointRestore",
    "CheckpointPolicy",
    "CheckpointWriter",
    "CheckpointDecision",
    "CheckpointPort",
    "CancellationPort",
    "CancellationGate",
    "CancellationToken",
    "CatalogError",
    "ContextEnvelope",
    "ContextOverflowError",
    "ContextSegment",
    "CreateRunCommand",
    "ContinuationPort",
    "EventSpec",
    "ExecutionReceiptMessage",
    "FairScheduler",
    "InMemoryAdvisoryLock",
    "InMemoryRuntimeStore",
    "IntegrationCoordinator",
    "IntegrationItem",
    "IntegrationStart",
    "LockedModelBinding",
    "ModelAction",
    "NormalizationError",
    "NormalizedTurn",
    "OpenAICompatibleProvider",
    "PromptMessage",
    "ProviderError",
    "ProviderCallIdentity",
    "ProviderRegistry",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderToolCall",
    "ToolDefinition",
    "ReadySlice",
    "RecoveryCoordinator",
    "RecoveryCommandMessage",
    "RecoveryPlan",
    "RecoveryTrigger",
    "ResourcePool",
    "RepairRetryBudget",
    "RunActor",
    "RunState",
    "RuntimeEvent",
    "RuntimeMessage",
    "RuntimeSnapshot",
    "RuntimeApplication",
    "RuntimeStore",
    "PostgreSQLRuntimeStore",
    "SessionInputCommand",
    "SessionCancelled",
    "SessionExit",
    "SessionIdentity",
    "SessionResult",
    "SessionProvenance",
    "SessionSpec",
    "SessionState",
    "StaticTemplateCatalog",
    "StoreCommitError",
    "SupervisorAdviceKind",
    "SupervisorTrigger",
    "TokenUsage",
    "ToolGatewayPort",
    "ToolObservation",
    "UsageSink",
    "UsageReceipt",
    "DEFAULT_TOOL_DEFINITIONS",
    "advice_proposal_hash",
    "build_report",
    "evaluate_advice",
    "evaluate_budget",
    "ensure_context_fits",
    "estimate_net_input_tokens",
    "main",
    "restore_checkpoint",
    "PostgreSQLAdvisoryLock",
    "run_from_environment",
    "normalize_response",
    "render_prompt",
    "prompt_text",
    "retry_delay_for_attempt",
    "supervisor_triggers",
    "validate_session_admission",
]
